spring:
  application:
    name: fds-spring-server

  # 1. MariaDB 연결 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/fds_db
    username: fds_user
    password: fdspassword

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 클래스에 맞게 테이블 자동 생성/수정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 2. Redis 연결 설정
  data:
    redis:
      host: localhost
      port: 6379

  # 3. Kafka 연결 설정
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fds-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# JWT 설정
jwt:
  secret: "dGhpcyBpcyBhIHNlY3VyZSBzZWNyZXQga2V5IGZvciBmZHMgc3lzdGVt"  # Base64(256-bit) - 운영 시 반드시 교체
  access-token-expiration-ms: 1800000    # 30분
  refresh-token-expiration-ms: 604800000 # 7일